#!/usr/bin/env python3
"""Generate a minimal Molecule 'smoke test' scenario for every role.

For each mps.* collection's role (50 total), produce:
  roles/<role>/molecule/default/molecule.yml      # Debian 13 docker, ansible provisioner, ansible verifier
  roles/<role>/molecule/default/converge.yml       # runs the role with a synthetic users_catalog
  roles/<role>/molecule/default/verify.yml         # default 'did converge succeed' assertion
  roles/<role>/molecule/default/requirements.yml   # declares mps.* collection deps as Galaxy requirements

The generated tests are smoke tests: they verify the role runs to
completion without error, not that it produces specific artifacts.
Per-role semantic assertions (e.g. "the dotfiles file X exists") are
deferred to follow-up work.

Re-run idempotently: generates fresh content each time.
"""

import os
import re
import shutil
from pathlib import Path

ROOT = Path("/home/jb/repo/github/my-perfect-system")
COLLECTIONS = [
    "mps-base",
    "mps-os",
    "mps-users",
    "mps-optimize",
    "mps-terminal",
    "mps-development",
    "mps-desktop",
    "mps-hardening",
    "mps-backup",
]


def parse_dependencies(meta_text):
    """Extract role dependencies from meta/main.yml."""
    deps = []
    if not meta_text:
        return deps
    # Look for `dependencies:` followed by `- role: ...` lines.
    in_deps = False
    for raw in meta_text.splitlines():
        s = raw.rstrip()
        if s.startswith("dependencies:"):
            in_deps = True
            continue
        if in_deps:
            if not s or not s.startswith(" "):
                in_deps = False
                continue
            m = re.match(r"\s*-\s*role:\s*(\S+)", s)
            if m:
                deps.append(m.group(1))
    return deps


def render_molecule_yml(role_fqn):
    """Ansible-lint-friendly molecule.yml using Docker / Debian 13."""
    return f"""---
# Molecule scenario for {role_fqn}.
# Generated by manage/gen_molecule_scenarios.py.
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker

platforms:
  - name: {role_fqn.replace(".", "-")}
    image: geerlingguy/docker-debian13-ansible:latest
    privileged: false
    pre_build_image: false
    command: /bin/sh -c "while true; do sleep 1000; done"

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    group_vars:
      all:
        ansible_user: root
        # users_catalog is filled in converge.yml per-role

verifier:
  name: ansible
  playbooks:
    verify: verify.yml
"""


def render_converge_yml(role_fqn, deps):
    """Run the role with a synthetic users_catalog (one user, no opt-ins)."""
    role_short = role_fqn.split(".")[-1]
    coll_short = role_fqn.split(".")[1]
    # The role is invoked under its FQN. Use galaxy-installed collection.
    return f"""---
# Minimal converge: invoke the role with default vars + a synthetic user
# so identity-resolved consumers see something without enabling all roles.

- name: Converge
  hosts: all
  become: true
  vars:
    users_catalog:
      molecule_user:
        user_roles: {{}}
    users_list:
      - name: molecule_user
  roles:
    - role: {role_fqn}
"""


def render_verify_yml(role_fqn):
    """Default verify: just confirm ansible ran without failure.

    Per-role assertions (file existence, package state, etc.) belong in
    dedicated verify playbooks once we expand beyond smoke tests.
    """
    return f"""---
# Default verify: smoke-test passes if converge completed without error.
# Replace with role-specific assertions (stat / package / command) when
# adding semantic tests.

- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Converge completed successfully
      ansible.builtin.debug:
        msg: "Smoke test for {role_fqn} passed (converge ran without error)."
"""


def render_requirements_yml(deps):
    """Declares mps.* collection deps for molecule to install before converge.

    Role refs like `mps.base.identity` map to the *collection* `mps.base`.
    """
    # Sort, dedupe, drop empties.
    collections = []
    for d in deps:
        if not d:
            continue
        # `d` may be `mps.base.identity` (a role) or `community.general` (a collection).
        # Galaxy requirements only take collections, so we strip the role tail.
        parts = d.split(".")
        if len(parts) >= 3 and parts[0] == "mps":
            collection_name = f"{parts[0]}.{parts[1]}"
        elif len(parts) == 2:
            collection_name = d
        else:
            continue
        if collection_name not in collections:
            collections.append(collection_name)
    if not collections:
        return None
    lines = ["---", "# Galaxy collections required by this role.", "# Generated."]
    lines.append("collections:")
    for c in collections:
        lines.append(f"  - name: {c}")
    lines.append("")
    return "\n".join(lines)


def is_role_skippable(meta_path):
    """Roles that fail fast on Debian 13 (assert_debian13) or whose deps
    are too heavy to exercise in a smoke test are skipped — but we still
    produce the scenario skeleton so dev/CI can extend later.
    """
    return False  # generate everything


def process_role(coll_name, role):
    coll_dir = ROOT / coll_name
    role_dir = coll_dir / "roles" / role
    fqn = f"mps.{coll_name.replace('mps-', '')}.{role}"

    if not role_dir.is_dir():
        return None

    # Read meta/main.yml for dependencies.
    meta_path = role_dir / "meta" / "main.yml"
    meta_text = meta_path.read_text() if meta_path.exists() else ""
    deps = parse_dependencies(meta_text)

    if is_role_skippable(meta_path):
        return f"SKIP {fqn}"

    # Write molecule scenario.
    scenario_dir = role_dir / "molecule" / "default"
    scenario_dir.mkdir(parents=True, exist_ok=True)

    (scenario_dir / "molecule.yml").write_text(render_molecule_yml(fqn))
    (scenario_dir / "converge.yml").write_text(render_converge_yml(fqn, deps))
    (scenario_dir / "verify.yml").write_text(render_verify_yml(fqn))
    req_yml = render_requirements_yml(deps)
    if req_yml is not None:
        (scenario_dir / "requirements.yml").write_text(req_yml)

    # Count files written.
    n = 3 if req_yml is None else 4
    return f"{fqn}: {n} files"


def main():
    print("Generating Molecule scenarios for every role...")
    total = 0
    written = 0
    skipped = 0
    for coll in COLLECTIONS:
        roles_dir = ROOT / coll / "roles"
        if not roles_dir.is_dir():
            continue
        for role_dir in sorted(roles_dir.iterdir()):
            if not role_dir.is_dir():
                continue
            total += 1
            result = process_role(coll, role_dir.name)
            if result is None:
                continue
            if result.startswith("SKIP"):
                skipped += 1
                print(f"  {result}")
            else:
                written += 1
                print(f"  {result}")
    print(f"\nTotal: {total} roles, {written} scenarios written, {skipped} skipped")


if __name__ == "__main__":
    main()
